language: python
services: docker

env:
  global:
    - ROLE_NAME: ddclient
    - secure: jJY+4xzC6OR9YVkavhXNocIvZHHzbattNJODwxgbL0psIJXoBxSYNFqFtmF3TaiYlacwOEOsJxj7m484OqPAoyXRyMvQpWhPVHvPh5/F2rYk5vR6/IOwvEU7CqUf/HYuokWsHvWHHqgYRHmj55639PurvnCD2mWG672eZf3k9gzDQ+mN2q7n2iyaPXr+c9RAnjdnjsJrCwp0XD7GxDMAstLz4LZ4Cb+6bHXhoewSy9Dvgs08wUO1lONV5Qi8hzpvQ7QEhegS8VRoCAGmPMtF3TfJmHBtCNzNQ/IPCsjJEdcTrIm1AeNcE+9oy10moC4qNnY+5qQgUeApBEWGdALcvTvt8hAAfwu52wWILTwNyFPsB437+WCNcdE1owp4okcb/4BbVsvX7js/N+WuRF553CryrbDjgqvwjlvex28IQ1z+ZrxO7gm/yzAqsXozjj93Z/bUvTZv0vuymOWB0KbAnUpS1qRvw8bAE3AeyYY1TsqVeLCO1EDmg6JDLRNvuz8NJ3w4s6HudwX0A9W9mY3fjziqJbOalbEMv/TCqI628xSKsy2ae9EMY+1QcPjXC2HptiXNX5HERh6hXhdQ4dtvSMye+nMMXYHj3Rv2+ekGac8d5nfwusFZbHAFBYpTOmQVwDgMQhwqZefO9ar77IuSdb+XRhaqGULDq+HGGW21uZU=
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: debian10

before_install:
- openssl aes-256-cbc -k "$vault_file_pass" -in molecule/default/.vault_pass.txt.enc -out molecule/default/.vault_pass.txt -d
- sudo apt-get update -qq
- sudo apt-get install -qq python-apt python
- sudo -H pip install --upgrade urllib3[secure] pyopenssl

install:
- pip install molecule docker

before_script:
- cd ../
- mv ansible-role-$ROLE_NAME jpartain89.$ROLE_NAME
- cd jpartain89.$ROLE_NAME

script:
- molecule test

after_script:
- shred molecule/default/.vault_pass.txt

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: kK0MF6AhyPLEXkhFFjneCKbtmddeZnD3XbRHWUYqkIhKuwBaNq0q52mrHYug4X3xDYW4n84gFqUjcUoazA5X80WRp4KseVejKNShQ7zZDwiapneWRVxUbgvr0Xet5rLmgDP5qDnoiGOz2BDIJAn04HCgULwG5cZfeBJVJIR84leRixyl8MmomgvBEHV6hvwrbSdEGLP4ilaD5OgFJOE7bgyzcd9gyQ5AQclChTGqMRCibNpRwe0jbMRvGpFVCzewMSS4LapSfwCV8rRj+6P59pO44chmyiM9lADZg0O0JVhyp6RnyCgF/Ocg35XQ2tadInjy8Nlft73hpwo/b5zGn7UXxT0d7sXEYGGJbn5gZ8BUuzougLKZ9n3kGvXUEBF0J1mBYYhpLS3ue+hVQgdHhMV/Rl+GpBZWmuX2IzlIV611q+8OtsXPzO0uCYhM8BgXTSu8iiA4Jn2AoC5zNRcN5QPlZFcr73sKG8KjcG74YI+6Nb9HqflmrOawL2SLjWCNl2PFgkeyT/twBRYtpaT/ruTKuS9Q6drDIeKtEtJbnPIN/DAnTZq7m5kMWVBUaTtUpFMNM5/DTlgyTne2iB00hXibbfQ7i0epzfUYffYkvfhzC5LRk+/bq9iyIG4wpksFkwsGmHFTk2Pkiveb2ganWRY83zbLqtJ9CLlwGoUtYUw=
