---
# ddclient/tasks/main.yml

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_facts['os_family'] + '-' + ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['os_family'] }}.yml"

- import_tasks: git_prepare.yml
  when: ddclient_install_from_git

- import_tasks: install_from_git.yml
  when: ddclient_install_from_git

- import_tasks: install_from_package.yml
  when: not ddclient_install_from_git

- name: Build Out ddclient.conf File
  template:
    src: ddclient.conf.j2
    dest: "{{ ddclient_file.directory }}/{{ ddclient_file.file }}"
    owner: root
    group: root
  become: true
  #notify: Restart DDClient

- name: Update Mode for New Files
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: file
  with_items:
    - { path: "{{ ddclient_file.directory }}/{{ ddclient_file.file }}", mode: "0700" }
    - { path: "{{ ddclient_exec }}", mode: "0775" }
  become: true

- name: Autostart DDClient Block
  block:
    - name: Autostart DDClient
      service:
        name: ddclient
        enabled: yes
        state: started
      ignore_errors: true
  rescue:
    - name: Show Output of Failed Service
      shell: 'ddclient -daemon=0 -debug -verbose -noquiet'
      register: _ddclient_systemd
    - debug: var=_ddclient_systemd
