---
# ddclient/tasks/main.yml

- name: Create ~/git Directory
  file:
    path: "{{ ansible_user_dir }}/git"
    state: directory
    owner: "{{ ansible_real_user_id }}"
    group: "{{ ansible_real_group_id }}"

- name: Clone DDClient's Git Repo
  git:
    repo: "{{ ddclient_git_repo_http }}"
    dest: "{{ ddclient_git_repo_dest }}"
    update: yes
    accept_hostkey: yes
  register: _ddclient_git_cloned

- import_tasks: install.yml

- name: Build Out ddclient.conf File
  template:
    src: ddclient.conf.j2
    dest: "{{ ddclient_conf.directory }}/{{ ddclient_conf.file }}"
    owner: root
    group: root
  become: true
  notify: Restart DDClient

- name: Update Mode for New Files
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    mode: "{{ item.mode }}"
    state: file
  with_items:
    - { path: "/etc/ddclient/ddclient.conf", mode: "0700" }
    - { path: "/usr/sbin/ddclient", mode: "0775" }
  become: true
