---

- name: Prepare
  hosts: all

  tasks:
    - name: Install Required Apps
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        update_cache: yes
        cache_valid_time: 86400
      with_items:
        - rsync
        - aptitude
